export const HookInlineFormStrings = {
  autoSavePending: "AutoSave Pending, please check for errors...",
  savePending: "Save Pending, please check for errors...",
  remaining: "remaining",
  saving: "Saving...",
  seeLess: "See less",
  expand: "Expand",
  required: "Required",
  save: "Save",
  cancel: "Cancel",
  create: "Create",
  update: "Update",
  na: "N/A",
  saveError: "Error saving form",
  confirm: "Confirm",
  linkTitleLabel: "Link Title",
  linkUrlLabel: "Link URL",
  add: "Add",
  edit: "Edit",
  deleteLabel: "Delete",
  remove: "Remove",
  unknown: "Unknown",
  close: "Close",
  loading: "Loading",
  noResultsFound: "No results found",
  clickToClear: "Click here to Clear",
  clear: "Clear",
  urlRequired: "Invalid Url (http/https required)",
  openExpandedTextEditor: "Open Expanded Editor",
  closeExpandedTextEditor: "Close Expanded Editor",
  unsavedChanges: "Unsaved Changes",
  returnToEditing: "Return to Editing",
  dontSave: "Don't save",
  overview: "Overview",
  saveChangesTo: (title: string) => `Do you want to save your changes to ${title}?`,
  by: "by",
};
